library_app/urls.py
import imp
from unicodedata import name
from django.urls import path

from . import views

app_name='library_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search_query, name='search_query'),
    path('detail/<int:book_id>', views.detail, name='detail'),
    path('characters/', views.characters, name='characters'),
    path('add-to-cart/<int:book_id>', views.add_to_cart, name='add_to_cart'),
    path('update-cart/<int:checkout_item_id>', views.update_cart, name='update_cart'),
    path('remove-from-cart/<int:checkout_item_id>', views.remove_from_cart, name='remove_from_cart'),
    path('character/<int:character_id>', views.character, name='character'),
    path('like/<int:book_id>', views.like, name='like'),

]

library_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('library_app.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users_app.urls')),
    # path('', include('library_app.urls')),
]

users_app/urls.py
from django.urls import path


from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile')
]

templates/partials/_navbar.html
{% load static %}
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start p-3 px-5"
  style="background-color: #b40001;">
  <a class="d-flex align-items-center" href="{% url 'library_app:index' %}"><img
      src="/static/images/icons8-marvel-50.png" class="" alt="" style="height: 3rem;"></a>
  <ul class="nav col-12 col-lg-auto me-lg-auto justify-content-center">
  </ul>
  <form class="col-12 col-lg-auto me-lg-3 mb-3 mb-lg-0" action="{% url 'library_app:search_query' %}" method="POST">
    <input class="form-control form-control-dark" name="search-query" id="search-query" type="text"
      placeholder="Search..." aria-label="Search" style="font-style: italic;">
    {% csrf_token %}
  </form>
  {% if request.user.is_authenticated %}
  <div class="text-end h-auto">
    <button class="btn me-2 btn-warning"><a class="text-decoration-none text-dark"
        href="{% url 'users_app:logout' %}">Logout</a></button>
    <a class="text-decoration-none text-dark" href="{% url 'users_app:profile' user.username %}"> <img
        src="/static/images/icons8-shopping-cart-30.png" alt=""></a>
  </div>
  {% endif %}
  {% if not request.user.is_authenticated %}
  <div class="text-end">
    <button class="btn btn-dark me-2"><a class="text-decoration-none text-light"
        href="{% url 'users_app:login' %}">Login</a></button>
    <button class="btn btn-warning"><a class="text-decoration-none text-dark"
        href="{% url 'users_app:register' %}">Register</a></button>
  </div>
  {% endif %}
</div>

templates/partials/footer.html
{%load static%}
<footer class="position-relative w-100 p-0 m-0">
<div class="bg-dark p-2">
  <a href="https://www.marvel.com/" class="text-decoration-none"><p class="text-center text-muted m-0 p-0">Data provided by Marvel. © 2022 MARVEL</p></a>
</div>
</footer>

templates/partials/paginator.html
{% load static %}
<nav aria-label="Page navigation example" class="m-0">
  <ul class="pagination justify-content-center align-items-center p-0 m-0">
    <li class="d-flex align-items-center page-item {% if not products_page.has_previous %} disabled {% endif %}">
      <a href="?page_num=1" href="#" class="page-link" tabindex="-1">&laquo; First</a>
      <a class="page-link rounded-0" {% if products_page.has_previous %}
        href="?page_num={{products_page.previous_page_number}}" {% endif %}>
        Previous</a>
    </li>

    <li class="page-item">
      <a href="#" class="page-link rounded-0">{{products_page.number}}</a>
    </li>
    <li class="d-flex align-items-center page-item {% if not products_page.has_next %} disabled {% endif %}">
      <a class="page-item page-link rounded-0" {% if products_page.has_next %}
        href="?page_num={{products_page.next_page_number}}" {% endif %}>Next</a><a
        href="?page_num={{products_page.paginator.num_pages}}" tabindex="-1" class="page-link">Last
        &raquo;</a>
    </li>
  </ul>
</nav>