library_app/urls.py
import imp
from unicodedata import name
from django.urls import path

from . import views

app_name='library_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search_query, name='search_query'),
    path('detail/<int:book_id>', views.detail, name='detail'),
    path('characters/', views.characters, name='characters'),
    path('add-to-cart/<int:book_id>', views.add_to_cart, name='add_to_cart'),
    path('update-cart/<int:checkout_item_id>', views.update_cart, name='update_cart'),
    path('remove-from-cart/<int:checkout_item_id>', views.remove_from_cart, name='remove_from_cart'),
    path('character/<int:character_id>', views.character, name='character'),
    path('like/<int:book_id>', views.like, name='like'),

]

library_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('library_app.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users_app.urls')),
    # path('', include('library_app.urls')),
]

users_app/urls.py
from django.urls import path


from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile')
]

templates/users/login.html
{% extends 'base.html' %} {% block content %}

<form action="{% url 'users_app:login' %}" method="POST"
  class="d-flex flex-column align-items-center justify-content-center" style="height: 90vh;">
  <h1 class="text-center">Log in</h1>
  <fieldset>
    <label for="id_username"></label>
    {{form.username}}
  </fieldset>
  <fieldset>
    <label for="id_password"></label>
    {{form.password}}
  </fieldset>
  {% csrf_token %}
  <button type="submit" class="btn btn-danger mt-4">Log in</button>
</form>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container min-vh-100">
  <div class="row pt-4">
    <div class="col-3">
      <h4>Comic book</h4>
    </div>
    <div class="col-3 text-center d-sm-none d-md-block d-none d-sm-block">
      <h4>Price</h4>
    </div>
  </div>
  {% for checkout_item in user.checkout.checkout_items.all %}
  <div class="row pt-3">
    <div class="col-3 d-flex align-items-center border-top">
      <img
        src="{{checkout_item.book.image_url}}"
        alt="{{checkout_item.book.id}}"
        class=""
        width="100"
      />
      <div class="col-6">
        <h4
          class="m-0 flex-column d-none d-lg-block justify-content-center align-self-center text-center flex-md-row fs-6"
        >
          {{checkout_item.book.title}}
        </h4>
      </div>
      <div class="col-2 col-sm-2 d-flex justify-content-center">
        <a href="{% url 'library_app:remove_from_cart' checkout_item.id %}">
          <i class="far fa-solid fa-x text-danger pt-1"></i>
        </a>
      </div>
      <hr />
    </div>
    <div
      class="col-3 d-flex align-items-center justify-content-center text-center d-none d-sm-block d-sm-none d-md-block"
    >
      ${{checkout_item.book.price}}
    </div>
  </div>
  <div class="row pt-2">
    <div class="col-3">
      <form
        action="{% url 'library_app:update_cart' checkout_item.id %}"
        method="POST"
        class=""
      >
        <input
          type="number"
          name="quantity"
          value="{{checkout_item.quantity}}"
        />
        {% csrf_token %}
        <button type="submit" class="btn btn-sm btn-info">Update</button>
      </form>
    </div>
  </div>

  {% endfor %}
  <div class="row">
    <div class="col-4 d-flex justify-content-start">
      <h4>Total</h4>
    </div>
    <div class="col-3 d-flex justify-content-center">
      <h4>{{user.checkout.total_price}}</h4>
    </div>
  </div>
</div>
{% include 'partials/footer.html' %} {% endblock content %}

templates/users/register.html
{% extends 'base.html' %} {% block content %}

<form action="{% url 'users_app:register' %}" method="POST"
  class="d-flex flex-column align-items-center justify-content-center my-auto" style="height: 90vh;">
  <h1 class="text-center">Register</h1>
  <fieldset>
    <label for="id_username"></label>
    {{form.username}}
  </fieldset>

  <fieldset>
    <label for="id_password"></label>
    {{form.password}}
  </fieldset>

  {% csrf_token %}

  <button type="submit" class="btn btn-danger mt-4">Register</button>
</form>

{% endblock content %}