library_app/urls.py
import imp
from unicodedata import name
from django.urls import path

from . import views

app_name='library_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search_query, name='search_query'),
    path('detail/<int:book_id>', views.detail, name='detail'),
    path('characters/', views.characters, name='characters'),
    path('add-to-cart/<int:book_id>', views.add_to_cart, name='add_to_cart'),
    path('update-cart/<int:checkout_item_id>', views.update_cart, name='update_cart'),
    path('remove-from-cart/<int:checkout_item_id>', views.remove_from_cart, name='remove_from_cart'),
    path('character/<int:character_id>', views.character, name='character'),
    path('like/<int:book_id>', views.like, name='like'),

]

library_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('library_app.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users_app.urls')),
    # path('', include('library_app.urls')),
]

users_app/urls.py
from django.urls import path


from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile')
]

templates/catalog/character.html
{% extends 'base.html' %}{% load static %}{% block content %}

<div class="container-fluid min-vh-100">
  <h1 class="text-primary text-center py-4">{{character.name}}</h1>
  <div class="row justify-content-center mt-5">
    <div class="col-4 text-center">
      <img src="{{character.image}}" class="img-fluid" alt="..." />
    </div>
  </div>
  {% if character.description %}
  <div class="row pt-5 justify-content-center">
    <h3 class="text-center">BIO</h3>
    <div class="col-4">
      <p class="">{{character.description}}</p>
    </div>
  </div>
  {% endif %}
  {% if character.books.all %}
  <h4 class="text-primary text-center mt-4">More {{character.name}}</h4>
  <div class="row row-cols-1 row-cols-md-3 text-center pt-3">
    {% for book in character.books.all %}
    <div class="col">
      <a href="{% url 'library_app:detail' book.id %}" class="text-decoration-none related_chars"><img
          src="{{book.image_url}}" class="" alt="" style="width: 10rem;" />
        <h5 class="fs-6">{{book.title}}</h5>
      </a>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock content %}

templates/catalog/characters.html
{% extends 'base.html' %}{% load static %} {% block content %}
<div class="container mx-auto d-flex align-items-center justify-content-center m-5 p-4 min-vh-100">
  <div class="row text-center">
    {% for char in products_page %}
    <div class="col pt-2 hover_container m-4">
      <a href="{% url 'library_app:character' char.id %}" class="link_container">
        <img src="{{char.image}}" class="img_hover" style="width: 20rem;" title="{{char.name}}" alt="..." /></a>
      <a class="text-decoration-none" href="{% url 'library_app:character' char.id %}">
        <h5 class="text-dark book_title mt-2 fs-3">{{char.name}}</h5>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% include 'partials/paginator.html' %}
{% endblock content %}

templates/catalog/details.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid min-vh-100 m-0 p-0">
  <div class="row justify-content-center pt-5">
    <div class="col-3 justify-content-center">

      <div class="container  m-0 p-0">
        <img src="{{books.image_url}}" class="detail_image" alt="..." />
        {% if request.user.is_authenticated %}
        <div class="">
          <span id="like-count-{{books.id}}" class="fs-4 text-center">Likes: {{ books.likes.all.count }}
          </span>
        </div>
        <div class="text d-flex justify-content-center text-center my-auto">
          <a href="{% url 'library_app:add_to_cart' books.id %}" class=""><i
              class="fas fa-solid fa-cart-arrow-down mx-2 fa-2x"></i></a>
          {% if request.user in books.likes.all %}
          <i class="fas fa-solid fa-heart fa-beat mx-2 fa-2x text-danger like" id="like-{{books.id}}"></i>
          {% else %}
          <i class="fas fa-solid fa-heart fa-beat mx-2 fa-2x like text-primary" id="like-{{books.id}}"></i>
          {% endif %}
        </div>
        {% endif %}
      </div>
    </div>
    <div class="col-lg-6 col-md-3">
      <h3 class="">{{books.title}}</h3>
      <div class="d-none d-lg-block">
        {% for author in books.authors.all %} {{author.role}}: {{ author }}
        <br />
        {% endfor %}
      </div>
      <p class="">Description: {{books.description|truncatewords:30}}</p>
      <h3 class="align-items-end">{{books.date}}</h3>
    </div>
  </div>
  <h3 class="text-danger pb-4 border-top text-center fs-1">Characters in this comic</h3>
  <div class="row text-center row-cols-1 row-cols-md-3 justify-content-center">
    {% if books.characters.all %}

    {% for character in books.characters.all %}
    <div class="col mb-5 link_container">
      <a href="{% url 'library_app:character' character.id %}"><img src="{{character.image}}" class="" alt="..." /></a>
      <h5 class="">{{character.name}}</h5>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock content %}

templates/catalog/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="row justify-content-end text-center">
  <div class="col-4">
    <div class="dropdown mr-5">
      <button class="btn shadow-none" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
        aria-expanded="false">
        <img src="/static/images/icons8-slider-48.png" alt="">
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><a class="dropdown-item" href="{% url 'library_app:characters' %}">Characters</a></li>
        <li><a class="dropdown-item" href="{% url 'library_app:index' %}">Comics</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="container-fluid min-vh-100 p-0 m-0">
  {% if messages %}
  <div class="row text-center justify-content-center pt-4">
    <div class="col-4 lg-offset-4">
      {% for message in messages %}
      <div class="alert alert-primary" role="alert">
        {{message}}
      </div>
      {% endfor %}
    </div>

    {% endif %}

    <div class="row text-center m-5 justify-content-center">
      {% for book in products_page %}
      <div class="col m-4">
        <a href="{% url 'library_app:detail' book.id %}" class="link_container">
          <img src="{{book.image_url}}" class="img_hover" style="width: 19rem;" title="{{book.title}}" alt="..." /></a>
        <a class="text-decoration-none" href="{% url 'library_app:detail' book.id %}">
          <h5 class="text-dark book_title mt-2">{{book.title}}</h5>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% include 'partials/paginator.html' %}

{% endblock content %}

templates/catalog/search_query.html
{% extends 'base.html' %} {% load static %}
{% block content %}
<div class="container container-fluid min-vh-100 p-4">
    {% for comic in search_query %}
    <div class="row search_container p-3">
        <div class="col-lg-4">
            <a href="{% url 'library_app:detail' comic.id %}" class="img_hover"><img src="{{comic.image_url}}"
                    alt=""></a>
        </div>

        <div class="col-lg-3 my-auto">
            <h5>{{ comic.title }}</h5>
        </div>

    </div>
    <hr class="">
    {% endfor %}
</div>
{% include 'partials/footer.html' %}
{% endblock content %}